language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - python -m unittest discover

# SBOM configuration
jobs:
  include:
    - os: linux
      dist: focal
      addons:
        sbom:
          on:
            branch: sbom
          run_phase: after_success
          output_format: cyclonedx-json
          input_dir: /
          output_dir: /sbom/python
after_success:
  - echo "Build successful! Checking SBOM..."
  - ls -al /sbom-output
  - cat /sbom-output/sbom.txt
